### PR TITLE
Fix winsock2 compatibility for libvncserver

### PR DESCRIPTION
**Pull request by lvorobyov**
Replacing the data type for socket descriptors. Use the data type of the SOCKET to represent socket descriptors. Conditions for checking socket descriptors have been fixed in accordance with https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms740516(v=vs.85).aspx . This fixes the bug #165 . 
libvnc-win32
Note: IPv6 is disabled on Windows XP, so didn't create the IPv6 socket.
Note: You must add a firewall exception for port 5900. (Start -> Command palette -> Windows Firewall -> Exceptions)

### CODE REVIEW

**Comment by AlexiaChen** [comment]
OK , I  tried to fix it like this way, all the same.  but example.exe does not work fine.   the other issue pops up , so, I gave it up.

**Comment by bk138** [comment]
@AlexiaChen hint: it is not the data type, it is the handling of INVALID_SOCKET vs -1.

**Comment by whm200410** [comment]
Hi lvorobjev.
The files you changed is not enough, there are other files that deal with socket(int) should be changed also.
Or, it will cause crash

**Comment by DaburLal** [comment]
Hello, Can i download the version of source codes before these changes were made?? if yes, then how ?? Thank you!

**Comment by whm200410** [comment]
https://github.com/whm200410/libvncserver


you can download from this.




发自网易邮箱大师


On 1/11/2018 16:50，NoMad<notifications@github.com> wrote：

Hello, Can i download the version of source codes before these changes were made?? if yes, then how ?? Thank you!

**Comment by BastiaanOlij** [comment]
I'm playing around with this as well. Applying the patch does fix the socket issues for me but I'm getting errors about incorrect size when trying to connect to any of the examples with a vnc client

**Comment by whm200410** [comment]
Did this patch check in?

**Comment by bk138** [comment]
I plan to. I have a day job that takes a lot of time atm tough.

**Comment by alcz** [comment]
FYI, using i've merged the changes from @whm200410 https://github.com/whm200410/libvncserver
while managing to keep git pull/push workflow and also patched the multi-threading listener mode too. 

https://github.com/alcz/libvncserver/commits/master

Ligthly tested with current MSVC 2017. Probably it needs some further cleanup, at least to messy whitespaces in code, but I currently have no time to do it, sorry.

**Comment by sfhacker** [comment]
@alcz **FROM BAD TO WORSE**

Just tried to build these merged changes and I'm faced with these **ALARMING and LONG-STANDING** compilation errors:

Environment

- Windows 10
- Windows SDK 10.0
- cmake 3.8.1


$ make all
Scanning dependencies of target vncserver
[  1%] Building C object CMakeFiles/vncserver.dir/libvncserver/main.c.obj
In file included from C:/msys/1.0/src/libvncserver-master/libvncserver/main.c:16:0:
C:/msys/1.0/src/libvncserver-master/rfb/rfb.h:57:9: error: unknown type name 'UINT32'
 typedef UINT32 in_addr_t;
         ^~~~~~
C:/msys/1.0/src/libvncserver-master/rfb/rfb.h:57:16: error: conflicting types for 'in_addr_t'
 typedef UINT32 in_addr_t;
                ^~~~~~~~~
In file included from C:/msys/1.0/src/libvncserver-master/rfb/rfb.h:44:0,
                 from C:/msys/1.0/src/libvncserver-master/libvncserver/main.c:16:
C:/msys/1.0/src/libvncserver-master/rfb/rfbproto.h:114:18: note: previous declaration of 'in_addr_t' was here
 typedef uint32_t in_addr_t;
                  ^~~~~~~~~
In file included from C:/msys/1.0/src/libvncserver-master/libvncserver/main.c:16:0:
C:/msys/1.0/src/libvncserver-master/rfb/rfb.h:106:41: error: duplicate member 'conn'
 #define COND(cond)  CONDITION_VARIABLE (conn)
 
 
C:/msys/1.0/src/libvncserver-master/libvncserver/main.c:361:16: error: 'struct _rfbClientRec' has no member named 'updateCond'; did you mean 'updateBuf'?
      TSIGNAL(cl->updateCond);
                ^
C:/msys/1.0/src/libvncserver-master/rfb/rfb.h:104:49: note: in definition of macro 'TSIGNAL'
 #define TSIGNAL(cond)  WakeConditionVariable (&(cond))
                                                 ^~~~
C:/msys/1.0/src/libvncserver-master/libvncserver/main.c: In function 'rfbMarkRegionAsModified':
C:/msys/1.0/src/libvncserver-master/libvncserver/main.c:420:16: error: 'struct _rfbClientRec' has no member named 'updateCond'; did you mean 'updateBuf'?
      TSIGNAL(cl->updateCond);
                ^
				
C:/msys/1.0/src/libvncserver-master/libvncserver/rfbserver.c:3553:1: error: conflicting types for 'rfbNewUDPConnection'
 rfbNewUDPConnection(rfbScreenInfoPtr rfbScreen,
 ^~~~~~~~~~~~~~~~~~~
 
 
C:/msys/1.0/src/libvncserver-master/libvncserver/sockets.c:1101:1: error: conflicting types for 'rfbSetNonBlocking'
 rfbSetNonBlocking(SOCKET sock)
 ^~~~~~~~~~~~~~~~~
 
 
C:/msys/1.0/src/libvncserver-master/libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c:26:17: fatal error: pwd.h: No such file or directory
 #include <pwd.h>
                 ^
compilation terminated.


C:/msys/1.0/src/libvncserver-master/libvncserver/tightvnc-filetransfer/filetransfermsg.h:52:6: error: conflicting types for 'CreateDirectoryA'
 void CreateDirectory(char* dirName);
 
 
In file included from C:/msys/1.0/src/libvncserver-master/libvncclient/cursor.c:25:0:
C:/msys/1.0/src/libvncserver-master/rfb/rfbclient.h:247:2: error: unknown type name 'SOCKET'
  SOCKET sock;
  ^~~~~~
C:/msys/1.0/src/libvncserver-master/rfb/rfbclient.h:383:2: error: unknown type name 'SOCKET'
  SOCKET listenSock;
  ^~~~~~
In file included from C:/msys/1.0/src/libvncserver-master/libvncclient/cursor.c:25:0:
C:/msys/1.0/src/libvncserver-master/rfb/rfbclient.h:637:8: error: unknown type name 'SOCKET'
 extern SOCKET ListenAtTcpPort(int port);
        ^~~~~~
		
In file included from C:/msys/1.0/src/libvncserver-master/libvncclient/rfbproto.c:38:0:
C:/msys/1.0/src/libvncserver-master/rfb/rfbclient.h:247:2: error: unknown type name 'SOCKET'
  SOCKET sock;
  ^~~~~~
  
In file included from C:/msys/1.0/src/libvncserver-master/libvncclient/sockets.c:39:0:
C:/msys/1.0/src/libvncserver-master/rfb/rfbclient.h:247:2: error: unknown type name 'SOCKET'
  SOCKET sock;
  ^~~~~~
  
In file included from C:/msys/1.0/src/libvncserver-master/libvncclient/tls_openssl.c:25:0:
C:/msys/1.0/src/libvncserver-master/rfb/rfbclient.h:247:2: error: unknown type name 'SOCKET'
  SOCKET sock;
  ^~~~~~
  
C:/msys/1.0/src/libvncserver-master/rfb/rfbclient.h:247:2: error: unknown type name 'SOCKET'
  SOCKET sock;
  ^~~~~~
  
  
[ 90%] Linking C executable examples/filetransfer.exe
libvncserver.a(handlefiletransferrequest.c.obj):handlefiletransferrequest.c:(.text+0x295): undefined reference to `getpwuid'
libvncserver.a(handlefiletransferrequest.c.obj):handlefiletransferrequest.c:(.text+0x2c6): undefined reference to `geteuid'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [examples/filetransfer.exe] Error 1
make[1]: *** [CMakeFiles/examples_filetransfer.dir/all] Error 2
make: *** [all] Error 2

The embarrassing question is: has this project ever being built from source and tested?

**Comment by sfhacker** [comment]
@whm200410 Just tried to compile your fork. Not my lucky day at all.
Have a look at: https://github.com/whm200410/libvncserver/issues/2

Cheers.

**Comment by alcz** [comment]
Instructions from @whm200410 are saying, you have to at least define LIBVNCSERVER_HAVE_LIBPTHREAD.
It's somewhat mentioned at https://github.com/whm200410/libvncserver/blob/master/README.md
HTH

**Comment by frodak17** [comment]
While it indeed compiles and runs it appears to have other issues.  When a client connects with the server, the server returns the wrong desktop size.  Then the server will crash because there are still places where an invalid socket handle is used when closing the socket.

**Comment by sfhacker** [comment]
We are still waiting to learn how to proceed with these compilation and linking errors. This pull request is 11 months old, How can we help this project move forward? Cheers.

**Comment by alcz** [comment]
@frodak17 Could kindly point out in the source code which specific lines have invalid socket type?
Let's say starting point of modifications are as follows:
https://github.com/LibVNC/libvncserver/compare/master...alcz:master

You can mark specific lines like this:
https://github.com/alcz/libvncserver/blob/master/libvncserver/sockets.c#L105-L118

Without good feedback, it would be hard to fix anything. I've used this code with custom framebuffer (not the Windows desktop) and it behaving quite okay.

**Comment by tobydox** [comment]
New attempt in #257

**Comment by tobydox** [comment]
New attempt in #257

**Comment by tobydox** [comment]
New attempt in #257

**Comment by tobydox** [comment]
FYI: pthreads/mingw64 compatibility is available via #354

**Comment by bk138** [comment]
Closing in favour of the more complete #257. But anyway, big thanks for a good starting point  @lvorobyov :+1:

**Pull request closed without merging**
