### PR TITLE
Various improvements for building with mingw64 toolchain

### PR DESCRIPTION
**Pull request by tobydox**
In combination with PR #353 and #257 these changes finally allow building functional libraries and tests using the mingw64 toolchain.

### CODE REVIEW

**Comment by bk138** [comment]
Will check during the holidays the latest, thanks!

**Comment by tobydox** [comment]
Any news? :)

**Comment by tobydox** [comment]
Updated the commits after #257 has been merged.

**Comment by bk138** [comment]
@tobydox which toolchain file are you using? Is there one you can recommend for Debian Buster?

**Comment by tobydox** [comment]
Basically the toolchain files used for Veyon (on Debian Buster) are similar: https://github.com/veyon/veyon/blob/master/cmake/modules/Win64Toolchain.cmake and https://github.com/veyon/veyon/blob/master/cmake/modules/MinGWCrossCompile.cmake. If you don't mind we can import an adapted version to libvnc.

`SHGetKnownFolderPath()` is part of `shell32.dll` which is probably an implicitly linked library in my toolchain. As of 4714daa6831bd4d841a24c4434cab4f4f259bf2b `shell32.dll` is now linked explicitely.

**Comment by bk138** [comment]
I still get `/usr/bin/i686-w64-mingw32-ld: libvncserver.a(handlefiletransferrequest.c.obj):handlefiletransferrequest.c:(.text+0x298): undefined reference to `SHGetKnownFolderPath'` with 

```

i686-w64-mingw32-gcc (GCC) 8.3-win32 20190406
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tobydox** [comment]
It looks like `_WIN32_WINNT` needs to be set to `0x0600` or higher (to enable support for Win32 API of Windows Vista and higher) and FOLDERID_Profile needs to be passed as a pointer. I updated the corresponding commit.

**Comment by bk138** [comment]
Closing this PR, most of the changes (and some more) are in fc4d16001f2bfdd21ff661c52d701b164beb4b2f. Thanks!

**Comment by tobydox** [comment]
Thanks for incorporating the changes! Is there a specific reason why b2dd5d39f50c9495a7aa627c21bc9dc4fb8a0796 is not included?

**Comment by tobydox** [comment]
BTW the CI additions for MinGW are great!

**Comment by bk138** [comment]
> Thanks for incorporating the changes! Is there a specific reason why [b2dd5d3](https://github.com/LibVNC/libvncserver/commit/b2dd5d39f50c9495a7aa627c21bc9dc4fb8a0796) is not included?

Yes. Mainly being overly cautious as users of the library might rely on the `LIBVNCSERVER_HAVE_WS2TCPIP_H` in their code. I totally agree that this should be remove at a later stage or declared obsolete now.

**Pull request closed without merging**
