### PR TITLE
BUGFIX: use WS_HYBI_HEADER_LEN_SHORT instead of WSHLENMAX to read header

### PR DESCRIPTION
**Pull request by Lightwars**
BUGFIX: Assuming the header is always a minimum of 14 Bytes long is not correct according to the RFC 6455 spec, it can be as short as 2 Bytes. Using it in combination with the RFB protocol, which tells that a client message can be as short as 6 Bytes, leads to reading past the end of a message. The proposal is to use WS_HYBI_HEADER_LEN_SHORT instead of WSHLENMAX to read only a minimum header, then reading the rest of the header if it is longer. Original finding here: https://github.com/LibVNC/libvncserver/issues/297

### CODE REVIEW

**Comment by monitor6** [comment]
I think I found a smaller fix that might be worth considering(?). I replaced this line 

      int n = ((uint64_t)WSHLENMAX) - wsctx->header.nRead;

With

      int n;
      if (wsctx->header.nRead < WS_HYBI_HEADER_LEN_SHORT) {
        n = WS_HYBI_HEADER_LEN_SHORT - wsctx->header.nRead;
      } else {
        /* headerLen was set on previous call */
        n = wsctx->header.headerLen - wsctx->header.nRead;
      }

However this relies on server implementations to call webSocketsDecodeHybi multiple times when the payload len is >=126. So I'm not sure if this is considered fragile or bad practice.. 

In combination with x11vnc it seems to work well though, including receiving large clipboard items (sent using novnc).

**Comment by monitor6** [comment]
Correction, there are still some issues with large clipboards, I'm investigating them now. Though early testing shows that the code from the PR handles them much much beter than my attempt.

**Comment by monitor6** [comment]
The issue with large clipboards seems unrelated, so I opened a new issue about that. 

I've tested the code from the PR for a while now and for me it fixes the problem with mouse input, without complications :-)

**Comment by patrakov** [comment]
Why is it still not merged?

**Pull request merged**
