### PR TITLE
Fix multithreaded read/write with TLS for OpenSSL.

### PR DESCRIPTION
**Pull request by gujjwal00**
OpenSSL TLS context cannot be used for concurrent reading & writing from different threads. This was already reported in #100 . PR #118 fixes it for GnuTLS. 

I am facing the same issue with  LibreSSL & MultiVNC.

This PR wraps TLS read/write operations inside a mutex.

### CODE REVIEW

**Comment by bk138** [comment]
Isn't this handled by all the stuff in https://www.openssl.org/docs/man1.0.2/man3/CRYPTO_set_dynlock_lock_callback.html ?

**Comment by gujjwal00** [comment]
I thought so too. But MultiVNC was either crashing randomly (but always inside `SSL_read`/`SSL_write`) or data was corrupted. Searching (a lot) for errors pointed to threading issues. Then I found this limitation.

Essentially, 'thread safety' for OpenSSL means that:
1.  Library can be used in multi-threaded environment.
2.  Different threads can use **different** SSL context/object concurrently.
3.  Different threads can use **same** SSL context/object but **not** concurrently.

To get this 'thread safety' (and only this), we need to:
- Setup locking callbacks (before 1.1.0)
- Do nothing (since 1.1.0)

Since 1.1.0, OpenSSL handles this automatically and these [callbacks](https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-stable/include/openssl/crypto.h#L220-L261) are defined as no-op.

Reference:
https://www.openssl.org/blog/blog/2017/02/21/threads/

https://github.com/openssl/openssl/issues/2165

https://stackoverflow.com/questions/14467630/clarifying-openssl-0-9-8l-concurrency-support-can-ssl-instances-be-used-by-mul

**Comment by bk138** [comment]
Thanks for the in-depth explanation!

**Comment by gujjwal00** [comment]
Looks like some more work is needed on this 😞.
Still facing the issue described [here](http://openssl.6102.n7.nabble.com/RE-SSL-read-returning-SSL-ERROR-SYSCALL-with-errno-11-EAGAIN-td76518.html).

Following call to `SSL_get_error` uses the same SSL object:
https://github.com/LibVNC/libvncserver/blob/b254b1c18d9a891f4996a2b980fb1089e760d53b/libvncclient/tls_openssl.c#L122

We need to bring calls to `ssl_errno`  inside mutex protection. 

Will submit a PR after more testing.

**Comment by C8LUKA** [comment]
hi，sorry to disturb you， when i see the code you merged into.
it confused me ， which you usd global static mutex to lock the read and write op.
may be it`s better to lock the ssl connection by it`s own mutex.

**Comment by gujjwal00** [comment]
> hi，sorry to disturb you

No problem! Any feedback is always appreciated.

Thanks for pointing this out. I will try to fix this.

**Pull request merged**
