### PR TITLE
Add reverse connections in libvncclient

### PR DESCRIPTION
**Pull request by NDagestad**
This is a simple reverse connection implementation, if this is something you'd want, I can add reverse connection to the server too. (There are a few points that could be made better probably, comments are welcome)

### CODE REVIEW

**Comment by bk138** [comment]
I believe you got something mixed up here - a reverse VNC connections means the viewer (e.g. LibVNCClient) is [listening for a server to connect to it](https://help.ubuntu.com/community/VNC/Reverse). We already [have that](https://github.com/LibVNC/libvncserver/blob/master/libvncclient/listen.c), see [here](https://github.com/bk138/multivnc/blob/master/src/VNCConn.cpp#L288) for a complete listening viewer implementation.

**Comment by zeGrandpa** [comment]
I'm not sure how I missed that. 🤔 
Sorry for the noise then...

**Comment by NDagestad** [comment]
I'm not quite sure how sure how I missed something so obvious 🤔
Sorry for the noise then...

**Comment by bk138** [comment]
No problem - thanks for the contribution anyway!

**Pull request closed without merging**
