### PR TITLE
Install examples in BINDIR

### PR DESCRIPTION
**Pull request by sergiomb2**

### CODE REVIEW

**Comment by bk138** [comment]
I don't think installing the examples makes sense. Their intended audience is developers (which can build them from source) not users.

**Comment by sergiomb2** [comment]
that is the point, examples especially the client examples, have tools that looks very promising like SDLvncviewer,  vnc2mpg, camera, sshtunnel, filetransfer  etc (which I just discovered this weekend) 

they all lack the manual , but if is to much install in bin dir , can we install it in /usr/share/libvncserver ? 

thank you

**Comment by sergiomb2** [comment]
all -utils package on Fedora 

```
cat /var/log/rpmpkgs | grep "\-utils"
alsa-utils-1.2.10-1.fc38.x86_64.rpm
bind-dnssec-utils-9.18.19-1.fc38.x86_64.rpm
bind-utils-9.18.19-1.fc38.x86_64.rpm
bridge-utils-1.7.1-6.fc38.x86_64.rpm
caca-utils-0.99-0.69.beta20.fc38.x86_64.rpm
cifs-utils-7.0-1.fc38.x86_64.rpm
cifs-utils-info-7.0-1.fc38.x86_64.rpm
desktop-file-utils-0.26-8.fc38.x86_64.rpm
dnf-utils-4.4.3-1.fc38.noarch.rpm
docbook-utils-0.6.14-56.fc38.noarch.rpm
egl-utils-8.5.0-1.fc38.x86_64.rpm
fcoe-utils-1.0.34-4.gitb233050.fc38.x86_64.rpm
felix-utils-1.11.8-3.fc38.noarch.rpm
festival-freebsoft-utils-0.10-31.fc38.noarch.rpm
firebird-utils-4.0.2.2816-4.fc38.x86_64.rpm
glpk-utils-5.0-6.fc38.x86_64.rpm
glx-utils-8.5.0-1.fc38.x86_64.rpm
gnome-doc-utils-0.20.10-31.fc38.noarch.rpm
gnome-doc-utils-stylesheets-0.20.10-31.fc38.noarch.rpm
gnutls-utils-3.8.1-1.fc38.x86_64.rpm
ima-evm-utils-1.4-7.fc38.x86_64.rpm
iptables-utils-1.8.9-4.fc38.1.x86_64.rpm
irda-utils-0.9.18-44.fc38.x86_64.rpm
iscsi-initiator-utils-6.2.1.4-10.git2a8f9d8.fc38.x86_64.rpm
iscsi-initiator-utils-iscsiuio-6.2.1.4-10.git2a8f9d8.fc38.x86_64.rpm
isns-utils-libs-0.101-6.fc38.x86_64.rpm
java-diff-utils-4.12-2.fc38.noarch.rpm
kde-dev-utils-23.08.1-1.fc38.x86_64.rpm
kde-dev-utils-common-23.08.1-1.fc38.noarch.rpm
koji-utils-1.33.0-1.fc38.noarch.rpm
ldns-utils-1.8.3-6.fc38.x86_64.rpm
libblockdev-utils-2.28-5.fc38.x86_64.rpm
libdb-utils-5.3.28-55.fc38.x86_64.rpm
libjpeg-turbo-utils-2.1.4-2.fc38.x86_64.rpm
liblouisutdml-utils-2.11.0-4.fc38.x86_64.rpm
liblouis-utils-3.25.0-1.fc38.x86_64.rpm
libmbim-utils-1.28.4-1.fc38.x86_64.rpm
libmpeg3-utils-1.8-20.fc37.x86_64.rpm
libqmi-utils-1.32.4-1.fc38.x86_64.rpm
libselinux-utils-3.5-1.fc38.x86_64.rpm
libsndfile-utils-1.1.0-6.fc38.x86_64.rpm
libva-utils-2.18.2-1.fc38.x86_64.rpm
libvpx-utils-1.13.1-1.fc38.x86_64.rpm
maildir-utils-1.8.11-1.fc38.x86_64.rpm
mariadb-server-utils-10.5.22-1.fc38.x86_64.rpm
maven-shared-utils-3.3.4-6.fc38.noarch.rpm
ming-utils-0.4.9-0.9.20181112git5009802.fc34.x86_64.rpm
mtd-utils-2.1.4-4.fc38.x86_64.rpm
net-snmp-utils-5.9.3-2.fc38.x86_64.rpm
nfs-utils-2.6.3-1.rc3.fc38.x86_64.rpm
nilfs-utils-2.2.9-3.fc38.x86_64.rpm
ogre-utils-1.9.0-43.fc38.x86_64.rpm
opengl-games-utils-0.2-23.fc38.noarch.rpm
passwdqc-utils-2.0.3-1.fc38.x86_64.rpm
perl-utils-5.36.1-497.fc38.noarch.rpm
php-seld-phar-utils-1.2.1-2.fc38.noarch.rpm
pipewire-utils-0.3.85-1.fc38.x86_64.rpm
plexus-utils-3.4.2-2.fc38.noarch.rpm
policycoreutils-python-utils-3.5-1.fc38.noarch.rpm
poppler-utils-23.02.0-2.fc38.x86_64.rpm
pulseaudio-utils-16.1-4.fc38.x86_64.rpm
python3-utils-3.3.3-2.fc38.noarch.rpm
scl-utils-2.0.2-21.fc38.x86_64.rpm
sensible-utils-0.0.17-5.fc38.noarch.rpm
shadow-utils-4.13-6.fc38.x86_64.rpm
shadow-utils-subid-4.13-6.fc38.x86_64.rpm
smbios-utils-2.4.3-8.fc38.x86_64.rpm
smbios-utils-bin-2.4.3-8.fc38.x86_64.rpm
smbios-utils-python-2.4.3-8.fc38.x86_64.rpm
v4l-utils-1.22.1-5.fc38.x86_64.rpm
v4l-utils-devel-tools-1.22.1-5.fc38.x86_64.rpm
wayland-utils-1.2.0-1.fc38.x86_64.rpm
wimlib-utils-1.14.3-1.fc38.x86_64.rpm
xdg-utils-1.1.3-15.fc38.noarch.rpm
xorg-x11-font-utils-7.5-55.fc38.x86_64.rpm

rpm -q alsa-utils -l
/etc/alsa
/etc/alsa/alsactl.conf
/usr/bin/aconnect
/usr/bin/alsaloop
/usr/bin/alsamixer
/usr/bin/alsaunmute
/usr/bin/amidi
/usr/bin/amixer
/usr/bin/aplay
/usr/bin/aplaymidi
/usr/bin/arecord
/usr/bin/arecordmidi
/usr/bin/aseqdump
/usr/bin/aseqnet
/usr/bin/axfer
/usr/bin/iecset
/usr/bin/nhlt-dmic-info
/usr/bin/speaker-test

**Comment by bk138** [comment]
Mhm, I'm not convinced TBH. Those are utils for users, but https://github.com/LibVNC/libvncserver/blob/master/examples/server/example.c serve no user, their reason for being is to be informative to developers. We could maybe install the source code under the `share/doc` prefix to have the examples at hand when looking for docs in the installed package.

**Pull request closed without merging**
