### PR TITLE
CMake: Add the generation of cmake configuration files to apply to find_package

### PR DESCRIPTION
**Pull request by KangLin**
Add the generation of cmake configuration files to apply to find_package

See: https://cmake.org/cmake/help/v3.20/manual/cmake-packages.7.html

### CODE REVIEW

**Comment by bk138** [comment]
What's the relation to #446 ? Can you explain a bit please :-)

**Comment by KangLin** [comment]
It is a same. add descript of pull request.
Please merge it!

**Comment by bk138** [comment]
Will review time permitting, might take a while. Thanks for your contribution!

**Comment by bk138** [comment]
@KangLin which purpose does this addition serve? Can you explain a bit more please? Thanks so much!

**Comment by KangLin** [comment]
See: https://cmake.org/cmake/help/v3.20/manual/cmake-packages.7.html
This is the standard way of CMAKE to find the library. So that, need to add cmake configure file.
eg: [my program](https://github.com/KangLin/RabbitRemoteControl) depend it. see: 
https://github.com/KangLin/RabbitRemoteControl/blob/master/Plugins/LibVNCServer/Service/CMakeLists.txt
https://github.com/KangLin/RabbitRemoteControl/blob/master/Plugins/LibVNCServer/Viewer/CMakeLists.txt

**Comment by antenore** [comment]
Really neat @KangLin ! Good job

**Comment by bk138** [comment]
@KangLin I now found some time to try and test this out. It successfully installs the CMake configuration files and I'm able to use them in an example project, but I'm kinda stuck on what info the config provides.

Here's what i have:

```
find_package(LibVNCServer)
if(LibVNCServer_FOUND)
    message("LibVNCServer: ${LibVNCServer_FOUND} with version  ${LibVNCServer_VERSION} and include dirs  ${LibVNCServer_INCLUDE_DIRS}")
else()
    message("libVNCServer not found")
endif()
```

This gets me the version, but other vars seem to not be defined. I suspect lib and header location are accessible via properties, but that remains a bit unclear to me (and possibly future users). Can you add some explaining comments?

**Comment by KangLin** [comment]
Yes. the lib and header location are accessible via properties. only add export target of package to target_link_libraries, cmake will auotmation add lib and header to your link. 
The package file interface variables, please see:
https://cmake.org/cmake/help/v3.20/command/find_package.html#package-file-interface-variables

**Pull request merged**
